### PR TITLE
Removed wx dependencies for CLI apps

### PR DESCRIPTION
**Pull request by kinsamanka**
This allows running the CLI programs without the need to install wxPython4.

### CODE REVIEW

**Comment by etisserant** [comment]
Have you run test successfully with your changes ?
What is the benefit of your approach compared to just using provided "faxewx" module ?

**Comment by kinsamanka** [comment]
My tests are limited to the `Beremiz_cli.py` only. But so far I don't see any adverse effects on the GUI. 

The advantage over the `fakewx` module is that the GUI interface modules are not loaded at runtime. This simplifies the packaging of the CLI program.

**Comment by etisserant** [comment]
Please use gihub's actions to run tests if you can't run them locally. I won't pull any branch that do not pass tests.
Did you really run your CLI tests on a python interpreter where Wx is missing ?
The approach to use conditions to disable wx related code was discarded in favor of `fakewx` to avoid cluttering code with conditions everywhere.
I don't see relation with packaging. Please explain.

**Comment by kinsamanka** [comment]
Oh, I did not see the discussions about `fakewx`.

Please ignore this PR.

**Pull request closed without merging**
