### PR TITLE
WIP - Python3 development, do not merge

### PR DESCRIPTION
**Pull request by kinsamanka**
The main focus is to make the editor fully working on Python3.

All other features are not yet tested or converted.

### CODE REVIEW

**Comment by kinsamanka** [comment]
The standalone installer for testing can be found here:

https://gist.github.com/kinsamanka/e15385b3e714d24145f6f464d15860dd

Runs on Linux, OSX (x86_64 only) and 64-bit Windows.

Matiec compiler should be installed on the same directory.

Edit:
OSX has still some issues with the runtime code

**Comment by etisserant** [comment]
I see no twisted reactor being started in service.py. This is needed by SVGHMI, WAMP and runtime's configuration web interface. What's your plan for Beremiz_service.py ?

**Comment by kinsamanka** [comment]
I still have not decided on whether to rewrite it to python3 or replace it entirely with something that is future-proof.

**Comment by etisserant** [comment]
@kinsamanka many thanks for all the work on python3, and the XSLT fix. I merged everything I could from your changes, and now python3 is default branch of beremiz project.

**Pull request closed without merging**
